site_name: Airlane
theme: 'readthedocs'
pages:
- 'Top': 'index.md'
- 'Getting started': 'getting-started.md'
- 'Update view': 'update-view.md'
- 'Database': 'database.md'
- 'Test': 'test.md'
- 'Add routing': 'routing.md'